### ISSUE TITLE
Bug: ReferenceError: actual is not defined

### ISSUE THREAD

**Issue by mehdivk** [suchipi/chai-jest-snapshot#22]
Our snapshot tests are failing due to `ReferenceError: actual is not defined`. 

```
ReferenceError: actual is not defined
  at Proxy.matchSnapshot (node_modules/chai-jest-snapshot/dist/buildMatchSnapshot.js:45:12)
  at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
```

**Comment by suchipi** [comment]
This is fixed in `1.2.2`
